name       : python-natsort
version    : 8.2.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/n/natsort/natsort-8.2.0.tar.gz : 57f85b72c688b09e053cdac302dd5b5b53df5f73ae20b4874fcbffd8bf783d11
homepage   : https://github.com/SethMMorton/natsort
license    : MIT
component  : programming.python
summary    : Simple yet flexible natural sorting in Python
description: |
    Simple yet flexible natural sorting in Python.
rundeps    :
    - pyicu
build      : |
    %python3_setup
install    : |
    %python3_install
